#!/usr/bin/env python
"""Point the local tooling at a CloudFormation deployment (deploy/cloudformation/deepresearch.yaml).

Reads the stack outputs and writes
  config/stacks/<stack>.yaml         settings overlay (project, region, names, secret ids)
  config/stacks/<stack>.state.json   runtime state (gateway url, harness arn, queue, bucket, ...)
  config/stacks/<stack>.env          `source` it: exports DR_LOCAL_FILE / DR_DEPLOY_STATE / AWS_REGION
The existing config/local.yaml + config/deploy_state.json are never touched.

  python scripts/use_stack.py deepresearch-prod --region us-east-1
  source config/stacks/deepresearch-prod.env
  python scripts/mcp_connect.py --setup-profile && bash scripts/setup_claude_mcp.sh
  python scripts/live_research.py "..." --depth quick
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import boto3
import yaml

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "config" / "stacks"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("stack")
    ap.add_argument("--region", default=None, help="stack region (default: AWS_REGION / profile region)")
    ap.add_argument("--profile-name", default=None, help="local AWS profile name for the MCP client key (default <project>-mcp)")
    a = ap.parse_args()

    session = boto3.Session(region_name=a.region)
    region = session.region_name
    if not region:
        sys.exit("region unknown: pass --region")
    st = session.client("cloudformation").describe_stacks(StackName=a.stack)["Stacks"][0]
    if not st["StackStatus"].endswith("_COMPLETE") or "ROLLBACK" in st["StackStatus"]:
        print(f"warning: stack status is {st['StackStatus']}", file=sys.stderr)
    o = {x["OutputKey"]: x["OutputValue"] for x in st.get("Outputs", [])}
    project = o["Project"]
    harness_id = o["HarnessArn"].rsplit("/", 1)[-1]
    h = session.client("bedrock-agentcore-control").get_harness(harnessId=harness_id)["harness"]
    env = h.get("environment", {}).get("agentCoreRuntimeEnvironment", {})
    mem = (h.get("memory") or {}).get("managedMemoryConfiguration", {}).get("arn")

    overlay = {
        "project": project,
        "region": region,
        "stack": {"name": "", "region": ""},
        "gateway": {"region": region, "name": f"{project}-gw", "mcp_client_iam_user": f"{project}-mcp-client"},
        "harness": {"region": region, "name": h["harnessName"], "memory_mode": "managed" if mem else "disabled"},
        "queue": {"region": region, "name": f"{project}-intake", "dlq_name": f"{project}-intake-dlq"},
        "table": {"region": region, "name": o["TableName"]},
        "storage": {"bucket": o["BucketName"]},
        "dedupe": {"enabled": "ValkeySecretArn" in o, "lambda_name": o.get("DedupeFunctionName", f"{project}-dedupe"),
                   "valkey_secret_id": o.get("ValkeySecretArn", f"{project}/valkey")},
        "live": {"runtime_name": o["LiveRuntimeArn"].rsplit("/", 1)[-1].rsplit("-", 1)[0]},
        "notifications": {"sns_topic_name": o["SnsTopicArn"].rsplit(":", 1)[-1], "webhook_secret_id": o["WebhookSecretArn"]},
        "mcp_client": {"aws_profile": a.profile_name or f"{project}-mcp",
                       "secret_id": o.get("McpClientSecretArn", f"{project}/mcp-iam-key")},
    }
    state = {
        "stack_name": a.stack, "gateway_url": o["GatewayUrl"], "gateway_id": o["GatewayId"], "gateway_arn": o["GatewayArn"],
        "harness_arn": o["HarnessArn"], "harness_id": harness_id, "harness_runtime_id": env.get("agentRuntimeId"),
        "live_runtime_arn": o["LiveRuntimeArn"], "live_runtime_id": o["LiveRuntimeArn"].rsplit("/", 1)[-1],
        "queue_url": o["QueueUrl"], "dlq_url": o["DlqUrl"], "bucket": o["BucketName"], "table": o["TableName"],
        "sns_topic_arn": o["SnsTopicArn"], "webhook_secret_id": o["WebhookSecretArn"],
        "mcp_client_secret_id": o.get("McpClientSecretArn"), "skills_uri": o["ArtifactPrefix"] + "skills/deep-research-harness/",
        "memory_arn": mem, "dispatcher_log_group": o.get("DispatcherLogGroup"),
    }
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    ov, sf, ef = OUT_DIR / f"{a.stack}.yaml", OUT_DIR / f"{a.stack}.state.json", OUT_DIR / f"{a.stack}.env"
    ov.write_text(f"# generated by scripts/use_stack.py from CloudFormation stack {a.stack} ({region})\n"
                  + yaml.safe_dump(overlay, sort_keys=False, allow_unicode=True))
    sf.write_text(json.dumps({k: v for k, v in state.items() if v}, indent=2))
    ef.write_text(f"export DR_LOCAL_FILE={ov}\nexport DR_DEPLOY_STATE={sf}\nexport AWS_REGION={region}\nexport DR_REGION={region}\n"
                  f"export DR_MCP_PROFILE={overlay['mcp_client']['aws_profile']}\nexport NX_GATEWAY_URL={o['GatewayUrl']}\n")
    print(f"wrote {ov.relative_to(ROOT)}, {sf.relative_to(ROOT)}, {ef.relative_to(ROOT)}")
    print(f"\n  source {ef.relative_to(ROOT)}\n\nGateway: {o['GatewayUrl']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
